### ISSUE TITLE
Wrong version in Test-PerlTidy-20190309.001 release

### ISSUE THREAD

**Issue by aero** [shlomif/Test-PerlTidy#2]
Hi

You had released Test-PerlTidy-20190309.001 on CPAN.

But version number in the release is wrong.
See  https://metacpan.org/source/SHLOMIF/Test-PerlTidy-20190309.001/lib/Test/PerlTidy.pm#L22

**Comment by shlomif** [comment]
@aero : should be fixed now, thanks!
