### ISSUE TITLE
Request: option to pass extra config flags to Perl::Tidy

### ISSUE THREAD

**Issue by cxw42** [shlomif/Test-PerlTidy#3]
Thank you for this module, which is very useful!  I would like to do some custom tidying using a [`postfilter` in Perl::Tidy](https://metacpan.org/pod/Perl::Tidy#postfilter).  However, `is_file_tidy` does not permit passing `postfilter` to its Perl::Tidy instance:

https://github.com/shlomif/Test-PerlTidy/blob/9956f8fb5985db290055b5fca20abbd57255edcc/lib/Test/PerlTidy.pm#L57-L64

Would it be possible to add an argument to `is_file_tidy` and `run_tests` to pass a hashref of additional options for Perl::Tidy's constructor?

Thank you for considering this request!

-CXW

**Comment by shlomif** [comment]
Hi @cxw42 ! Thanks for the suggestion! Since I liked it, I minted a new release that should implement it: 20200411. Please test it and let me know if it works for you.

**Comment by cxw42** [comment]
Thanks very much for the quick response!  I have not tested `is_file_tidy`, but it works fine for `run_tests` :D .

**Comment by shlomif** [comment]
On Sat, 11 Apr 2020 08:58:17 -0700
Chris White <notifications@github.com> wrote:

> Thanks very much for the quick response!  I have not tested `is_file_tidy`,
> but it works fine for `run_tests` :D .
> 

You're welcome, and thanks for testing and resolving the ticket.

-- 

Shlomi Fish       https://www.shlomifish.org/
List of Networking Clients - https://shlom.in/net-clients

If Chuck Norris is disappointed by you not following his advice, he’ll survive.
On the other hand, you will not.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
