### ISSUE TITLE
Can't locate object method "visit" via package "Path::Tiny"

### ISSUE THREAD

**Issue by eserte** [shlomif/Test-PerlTidy#4]
On one of my smokers:
```
Can't locate object method "visit" via package "Path::Tiny" at /home/cpansand/.cpan/build/2020041204/Test-PerlTidy-20200411-_NjyLS/blib/lib/Test/PerlTidy.pm line 142.
# Looks like your test exited with 255 before it could output anything.
t/exclude_files.t ..... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
... (etc) ...
```

Probably happens if an old version of Path::Tiny is installed. According to https://metacpan.org/source/DAGOLDEN/Path-Tiny-0.112/Changes#L301 the visit() function was added in Path::Tiny 0.065, so this should be specified as minimum version.

**Comment by shlomif** [comment]
Thanks @eserte ! This should be fixed in version 20200412 .
