### ISSUE TITLE
Test failure since Perl::Tidy-20200822

### ISSUE THREAD

**Issue by ferki** [shlomif/Test-PerlTidy#5]
Looks like `t/is_file_tidy.t` fails since Perl::Tidy-20200822 with:

```
not ok 1 - t/tidy_file.txt

#   Failed test 't/tidy_file.txt'
#   at t/is_file_tidy.t line 17.
ok 2 - t/messy_file.txt
not ok 3 - pass perltidy_options perltidyrc named param

#   Failed test 'pass perltidy_options perltidyrc named param'
#   at t/is_file_tidy.t line 25.
# Looks like you failed 2 tests of 3.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests
```

I'm not sure how it would be best to fix yet, but still wanted to report it without an accompanying PR being in progress on my part.

**Comment by shlomif** [comment]
Hi @ferki ! Sorry for the late reply but it should be fixed in [release 20200930](https://metacpan.org/release/Test-PerlTidy). Please let me know if it works for you and this ticket can be closed. Thanks!

**Comment by ferki** [comment]
Hi @shlomif! No worries, I can confirm it now passes tests correctly on my end as well. Thanks for the fix! :heart:

**Comment by shlomif** [comment]
@ferki : thanks for confirming (and the fast reply). Closing.
