### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by depesz** [shlomif/Test-PerlTidy#6]
When I tried: cpanm Test::PerlTidy, I got:

```
=$ cpanm Test::PerlTidy 
--> Working on Test::PerlTidy
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Test-PerlTidy-20200930.tar.gz ... OK
Configuring Test-PerlTidy-20200930 ... OK
Building and testing Test-PerlTidy-20200930 ... FAIL
! Installing Test::PerlTidy failed. See /home/depesz/.cpanm/work/1625816787.41297/build.log for details. Retry with --force to force install it.
```

[build.log](https://github.com/shlomif/Test-PerlTidy/files/6789723/build.log)

Not entirely sure what to do with it now. Tried installing Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText but it also fails, not sure if it's related, though.

**Comment by shlomif** [comment]
Unset the `TEST_AUTHOR=1` env var.

**Comment by depesz** [comment]
Ah. obviously. Thanks.

**Comment by shlomif** [comment]
@depesz : also see https://github.com/shlomif/Test-PerlTidy/commit/8b5178de6eb12716697884cbbbaa93ee8c749da6 . thanks.
