### ISSUE TITLE
consider breaking the tie to a specific perltidy release

### ISSUE THREAD

**Issue by bikingcoder** [shlomif/Test-PerlTidy#9]
Hi, I think this library would be more useful if it could use a perltidy that's "in the environment" in someway, rather than arbitrarily forcing a version. The workflow is too awkward imo.

**Comment by shlomif** [comment]
@mcgaw : hi. if we do that, then the `t/*.t` tests will fail. also see: https://github.com/shlomif/supporting-older-perl5-releases .

**Comment by bikingcoder** [comment]
Never mind, I've just wrapped perltidy in a bit of bash for CI checking.
